---
# Source: jenkins/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stable-jenkins-2-5-3
  namespace: jenkins
  labels:
    "app.kubernetes.io/name": 'jenkins'
    "helm.sh/chart": "jenkins-2.5.4"
    "app.kubernetes.io/managed-by": "Helm"
    "app.kubernetes.io/instance": "stable-jenkins-2-5-3"
    "app.kubernetes.io/component": "jenkins-master"
