all:
  hosts:
    node1:
      ansible_host: 10.8.41.201
      ip: 10.8.41.201
      access_ip: 10.8.41.201
    node2:
      ansible_host: 10.8.41.202
      ip: 10.8.41.202
      access_ip: 10.8.41.202
    node3:
      ansible_host: 10.8.41.203
      ip: 10.8.41.203
      access_ip: 10.8.41.203
  children:
    mgrs:
      hosts:
        node1:
    mons:
      hosts:
        node1:
        node2:
        node3:
    osds:
      hosts:
        node1:
        node2:
        node3: