resources:
  - ./volumes/chartmuseum.yaml
  - ./volumes/registry.yaml
  - ./volumes/jobservice.yaml
  - ./database/database-secret.yaml
  - ./database/database-svc.yaml
  - ./database/database-ss.yaml
  - ./portal/deployment.yaml
  - ./portal/comfigmap.yaml
  - ./portal/service.yaml
  - ./notary/notary-secret.yaml
  - ./notary/notary-svc.yaml
  - ./notary/notary-signer.yaml
  - ./notary/notary-server.yaml
  - ./core/core-dpl.yaml
  - ./core/core-secret.yaml
  - ./core/core-svc.yaml
  - ./core/core-cm.yaml
  - ./ingress/ingress.yaml
  - ./ingress/secret.yaml
  - ./redis/service.yaml
  - ./redis/statefulset.yaml
  - ./jobservice/jobservice-cm.yaml
  - ./jobservice/jobservice-svc.yaml
  - ./jobservice/jobservice-cm-env.yaml
  - ./jobservice/jobservice-dpl.yaml
  - ./jobservice/jobservice-secrets.yaml
  - ./jobservice/jobservice-pvc.yaml
  - ./chartmuseum/chartmuseum-svc.yaml
  - ./chartmuseum/chartmuseum-dpl.yaml
  - ./chartmuseum/chartmuseum-secret.yaml
  - ./chartmuseum/chartmuseum-cm.yaml
  - ./chartmuseum/chartmuseum-pvc.yaml
  - ./clair/clair-secret.yaml
  - ./clair/clair-svc.yaml
  - ./clair/clair-dpl.yaml
  - ./registry/registry-svc.yaml
  - ./registry/registry-cm.yaml
  - ./registry/registry-dpl.yaml
  - ./registry/registry-pvc.yaml
  - ./registry/registry-secret.yaml
  - ./trivy/trivy-sts.yaml
  - ./trivy/trivy-secret.yaml
  - ./trivy/trivy-svc.yaml