---
# Source: wordpress/charts/mariadb/templates/master-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: bitnami-wordpress-9-3-15-mariadb
  labels:
    app: "mariadb"
    component: "master"
    chart: "mariadb-7.5.2"
    release: "bitnami-wordpress-9-3-15"
    heritage: "Helm"
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
  selector:
    app: "mariadb"
    component: "master"
    release: "bitnami-wordpress-9-3-15"
