---

os: linux

dist: bionic

language: shell

env:
  jobs:
    - MOLECULE_SCENARIO_NAME="ubuntu-18.04"

before_install:
  - |
    curl -Os https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_x86_64.deb
    curl -Os https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_SHA256SUMS
    curl -Os https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_SHA256SUMS.sig
    gpg --receive-key 51852D87348FFC4C
    gpg --verify vagrant_2.2.7_SHA256SUMS.sig vagrant_2.2.7_SHA256SUMS
    sha256sum -c vagrant_2.2.7_SHA256SUMS 2>&1 | grep OK
    sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev
    sudo dpkg -i vagrant_2.2.7_x86_64.deb
    sudo vagrant plugin install vagrant-libvirt
  - |
    sudo apt-get -y purge python3-openssl && sudo apt-get -y autoremove
    sudo apt-get update && sudo apt-get install -y ca-certificates curl gcc iproute2 pwgen python3 python3-dev sudo
    curl -skL https://bootstrap.pypa.io/get-pip.py | sudo -H python3
install:
  - |
    sudo make submodules_clean 
    sudo make submodules_init 
    sudo make submodules_sync 
    sudo make submodules_status
  - | 
    sudo make kubespray_venv 
    make kubespray_inventory_init
  - |
    # `source` Command does not exist! the command below will fail
    #     sudo make kubespray_inventory_build
    # Manually triggering the command(s)
    sudo source  ./venv/k8s/bin/activate;  cd ./submodule/kubespray && declare -a IPS=(10.8.41.101 10.8.41.102 10.8.41.103) && CONFIG_FILE=inventory/k8s/hosts.yaml python3 contrib/inventory_builder/inventory.py ${IPS[@]}
    pwd && cd ../../ && pwd
  - sudo make validate_vm _ENVIRONMENT=travis _VAGRANT_CFG=travis.vagrant_variable.yaml
  - sudo make up_vm _ENVIRONMENT=travis _VAGRANT_CFG=travis.vagrant_variable.yaml
  - sudo make status_vm
  - sudo make reload_vm
  - sudo make down
script:
  - |
    sudo make clean _ENVIRONMENT=travis
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/