---
# Source: logstash/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logstash-2-4-0
  labels:
    app: logstash
    chart: logstash-2.4.0
    release: logstash-2-4-0
    heritage: Helm
