---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - image: busybox
      name: busybox
      resources: {}
      command: ["/bin/sh"]
      args: ["-c", "sleep 600"]
      volumeMounts:
        - name: storageclass-nfs
          mountPath: /mnt/sharedfolder/storageclass-nfs
  volumes:
    - name: host-volume
      persistentVolumeClaim:
        claimName: pvc-storageclass-nfs