---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  labels:
    app.kubernetes.io/name: nfs
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    server: 10.8.41.11
    path: /mnt/sharedfolder/nfs
