---
# Source: harbor/templates/redis/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: stable-harbor-1-4-0-harbor-redis
  labels:
    heritage: Helm
    release: stable-harbor-1-4-0
    chart: harbor
    app: "harbor"
spec:
  ports:
    - port: 6379
  selector:
    release: stable-harbor-1-4-0
    app: "harbor"
    component: redis
