---
# Source: logstash/templates/poddisruptionbudget.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: logstash-2-4-0
  labels:
    app: logstash
    chart: logstash-2.4.0
    release: logstash-2-4-0
    heritage: Helm
spec:
  selector:
    matchLabels:
      app: logstash
      release: logstash-2-4-0
  maxUnavailable: 1
