---
# Source: logstash/templates/poddisruptionbudget.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "logstash-7-8-0-logstash-pdb"
  labels:
    app: "logstash-7-8-0-logstash"
    chart: "logstash"
    heritage: "Helm"
    release: "logstash-7-8-0"
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: "logstash-7-8-0-logstash"
