---
# Source: logstash/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "logstash-7-8-0-logstash"
  labels:
    app: "logstash-7-8-0-logstash"
    chart: "logstash"
    heritage: "Helm"
    release: "logstash-7-8-0"
