---
# Source: logstash/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: logstash-2-4-0
  labels:
    app: logstash
    chart: logstash-2.4.0
    release: logstash-2-4-0
    heritage: Helm
  annotations:
spec:
  type: ClusterIP
  ports:
    - name: beats
      port: 5044
      protocol: TCP
      targetPort: beats
  selector:
    app: logstash
    release: logstash-2-4-0
