---
# Source: logstash/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash-7-8-0-logstash
  labels:
    app: "logstash-7-8-0-logstash"
    chart: "logstash"
    heritage: "Helm"
    release: "logstash-7-8-0"
spec:
  serviceName: logstash-7-8-0-logstash
  selector:
    matchLabels:
      app: "logstash-7-8-0-logstash"
      release: "logstash-7-8-0"
  replicas: 1
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: "logstash-7-8-0-logstash"
      labels:
        app: "logstash-7-8-0-logstash"
        chart: "logstash"
        heritage: "Helm"
        release: "logstash-7-8-0"
      annotations:
        
        configchecksum: b3ea2970f209cf1ae1b76f1ebccf30b4abb6cfef805efc51d34d94c1654e333
        
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      serviceAccountName: "logstash-7-8-0-logstash"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - "logstash-7-8-0-logstash"
            topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 120
      volumes:
        - name: logstashconfig
          configMap:
            name: logstash-7-8-0-logstash-config
      hostAliases:
        - hostnames:
            - elasticsearch
          ip: elasticsearch-master-headless.elk.svc.cluster.local
      containers:
      - name: "logstash"
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
        image: "docker.elastic.co/logstash/logstash:7.8.0"
        imagePullPolicy: "IfNotPresent"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 300
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 3
          timeoutSeconds: 5
        ports:
        - name: http
          containerPort: 9600
        resources:
          limits:
            cpu: 1000m
            memory: 1536Mi
          requests:
            cpu: 100m
            memory: 1536Mi
        env:
          - name: LS_JAVA_OPTS
            value: "-Xmx1g -Xms1g"
        volumeMounts:
          - name: logstashconfig
            mountPath: /usr/share/logstash/config/data
            subPath: data
