---
# Source: harbor/templates/core/core-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: stable-harbor-1-4-0-harbor-core
  labels:
    heritage: Helm
    release: stable-harbor-1-4-0
    chart: harbor
    app: "harbor"
data:
  app.conf: |+
    appname = Harbor
    runmode = dev
    enablegzip = true

    [dev]
    httpport = 8080
  DATABASE_TYPE: "postgresql"
  POSTGRESQL_HOST: "stable-harbor-1-4-0-harbor-database"
  POSTGRESQL_PORT: "5432"
  POSTGRESQL_USERNAME: "postgres"
  POSTGRESQL_DATABASE: "registry"
  POSTGRESQL_SSLMODE: "disable"
  POSTGRESQL_MAX_IDLE_CONNS: "50"
  POSTGRESQL_MAX_OPEN_CONNS: "100"
  EXT_ENDPOINT: "harbor.k8s-1.vm"
  CORE_URL: "http://stable-harbor-1-4-0-harbor-core:80"
  JOBSERVICE_URL: "http://stable-harbor-1-4-0-harbor-jobservice"
  REGISTRY_URL: "http://stable-harbor-1-4-0-harbor-registry:5000"
  TOKEN_SERVICE_URL: "http://stable-harbor-1-4-0-harbor-core:80/service/token"
  WITH_NOTARY: "true"
  NOTARY_URL: "http://stable-harbor-1-4-0-harbor-notary-server:4443"
  CFG_EXPIRATION: "5"
  ADMIRAL_URL: "NA"
  WITH_CLAIR: "true"
  CLAIR_DB_HOST: "stable-harbor-1-4-0-harbor-database"
  CLAIR_DB_PORT: "5432"
  CLAIR_DB_USERNAME: "postgres"
  CLAIR_DB: "postgres"
  CLAIR_DB_SSLMODE: "disable"
  CLAIR_URL: "http://stable-harbor-1-4-0-harbor-clair:6060"
  CLAIR_ADAPTER_URL: "http://stable-harbor-1-4-0-harbor-clair:8080"
  WITH_TRIVY: "true"
  TRIVY_ADAPTER_URL: "http://stable-harbor-1-4-0-harbor-trivy:8080"
  REGISTRY_STORAGE_PROVIDER_NAME: "filesystem"
  WITH_CHARTMUSEUM: "true"
  CHART_REPOSITORY_URL: "http://stable-harbor-1-4-0-harbor-chartmuseum"
  LOG_LEVEL: "info"
  CONFIG_PATH: "/etc/core/app.conf"
  SYNC_REGISTRY: "false"
  CHART_CACHE_DRIVER: "redis"
  _REDIS_URL: "stable-harbor-1-4-0-harbor-redis:6379,100,"
  _REDIS_URL_REG: "redis://stable-harbor-1-4-0-harbor-redis:6379/2"
  PORTAL_URL: "http://stable-harbor-1-4-0-harbor-portal"
  REGISTRY_CONTROLLER_URL: "http://stable-harbor-1-4-0-harbor-registry:8080"
  REGISTRY_CREDENTIAL_USERNAME: "harbor_registry_user"
  CSRF_KEY: "CELk3iRjDSF3mch2gY6NOc4OVIs5gH2G"
  HTTP_PROXY: ""
  HTTPS_PROXY: ""
  NO_PROXY: "stable-harbor-1-4-0-harbor-core,stable-harbor-1-4-0-harbor-jobservice,stable-harbor-1-4-0-harbor-database,stable-harbor-1-4-0-harbor-chartmuseum,stable-harbor-1-4-0-harbor-clair,stable-harbor-1-4-0-harbor-notary-server,stable-harbor-1-4-0-harbor-notary-signer,stable-harbor-1-4-0-harbor-registry,stable-harbor-1-4-0-harbor-portal,127.0.0.1,localhost,.local,.internal"
