---
# Source: elastic-stack/charts/kibana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: stable-elk-2-0-1-kibana
  labels:
    app: kibana
    chart: "kibana-3.2.4"
    release: stable-elk-2-0-1
    heritage: Helm
data:
  kibana.yml: |
    elasticsearch.hosts: http://elasticsearch:9200
    server.host: "0"
    server.name: kibana
