---
# Source: elastic-stack/charts/kibana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
    chart: kibana-3.2.4
    release: stable-elk-2-0-1
    heritage: Helm
  name: stable-elk-2-0-1-kibana
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 5601
      protocol: TCP

  selector:
    app: kibana
    release: stable-elk-2-0-1
