all:
  hosts:
    node1:
      ansible_host: 10.8.41.101
      ip: 10.8.41.101
      access_ip: 10.8.41.101
    node2:
      ansible_host: 10.8.41.102
      ip: 10.8.41.102
      access_ip: 10.8.41.102
    node3:
      ansible_host: 10.8.41.103
      ip: 10.8.41.103
      access_ip: 10.8.41.103
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
