---
# Source: harbor/templates/clair/clair-dpl.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-harbor-1-4-0-harbor-clair
  labels:
    heritage: Helm
    release: stable-harbor-1-4-0
    chart: harbor
    app: "harbor"
    component: clair
spec:
  replicas: 1
  selector:
    matchLabels:
      release: stable-harbor-1-4-0
      app: "harbor"
      component: clair
  template:
    metadata:
      labels:
        heritage: Helm
        release: stable-harbor-1-4-0
        chart: harbor
        app: "harbor"
        component: clair
      annotations:
        checksum/secret: cd6909ad6b58999680b2dfb3c4194efb1221a911cb0fa2b2bf62099f708be37e
    spec:
      securityContext:
        fsGroup: 10000
      containers:
      - name: clair
        image: goharbor/clair-photon:v2.0.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 6061
          initialDelaySeconds: 300
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 6061
          initialDelaySeconds: 30
          periodSeconds: 10
        args: ["-log-level", "info"]
        env:
        - name: HTTP_PROXY
          value: ""
        - name: HTTPS_PROXY
          value: ""
        - name: NO_PROXY
          value: "stable-harbor-1-4-0-harbor-core,stable-harbor-1-4-0-harbor-jobservice,stable-harbor-1-4-0-harbor-database,stable-harbor-1-4-0-harbor-chartmuseum,stable-harbor-1-4-0-harbor-clair,stable-harbor-1-4-0-harbor-notary-server,stable-harbor-1-4-0-harbor-notary-signer,stable-harbor-1-4-0-harbor-registry,stable-harbor-1-4-0-harbor-portal,127.0.0.1,localhost,.local,.internal"
        ports:
        - containerPort: 6060
        volumeMounts:
        - name: config
          mountPath: /etc/clair/config.yaml
          subPath: config.yaml
      - name: adapter
        image: goharbor/clair-adapter-photon:v2.0.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /probe/healthy
            scheme: HTTP
            port: 8080
          initialDelaySeconds: 300
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /probe/ready
            scheme: HTTP
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        env:
        - name: SCANNER_CLAIR_URL
          # To avoid a pod cannot reach itself via service IP when the clusters disable hairpin
          value: "http://127.0.0.1:6060"
        - name: SCANNER_STORE_REDIS_URL
          valueFrom:
              secretKeyRef:
                name: stable-harbor-1-4-0-harbor-clair
                key: redis
        - name: SCANNER_CLAIR_DATABASE_URL
          valueFrom:
              secretKeyRef:
                name: stable-harbor-1-4-0-harbor-clair
                key: database
        - name: SCANNER_LOG_LEVEL
          value: "info"
        ports:
        - containerPort: 8080
      volumes:
      - name: config
        secret:
          secretName: "stable-harbor-1-4-0-harbor-clair"
