# -*- mode: ruby -*-
# vi: set ft=ruby :
HOSTNAME = "local"
PRIVATE_SUBNET = "10.8.41"
PUBLIC_SUBNET = "172.17.8"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  

  config.vm.define "#{HOSTNAME}-1" do |node|
    node.vagrant.plugins = ["dns"]
    node.dns.tld = "vm"
    node.dns.patterns = [/^(\w+\.)*#{HOSTNAME}-1\.vm$/]
    node.ssh.insert_key = false
    # The most common configuration options are documented and commented below.
    # For a complete reference, please see the online documentation at
    # https://docs.vagrantup.com.
    node.vm.hostname = "#{HOSTNAME}-1"

    node.vm.box = "ubuntu/bionic64"
    node.vm.network "forwarded_port", guest: 22, host: 2525
    node.vm.network :private_network, ip: "#{PRIVATE_SUBNET}.10"
    # node.vm.network :private_network, ip: "#{PUBLIC_SUBNET}.10"
    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://vagrantcloud.com/search.

    node.vm.synced_folder "./data/conf.d", "/etc/nginx/conf.d/", 
    type: "sshfs", 
    sshfs_opts_append: "-o nonempty -o cache=no"

    node.vm.synced_folder "./data/certs", "/etc/letsencrypt/live/", 
    type: "sshfs", 
    sshfs_opts_append: "-o nonempty -o cache=no"

    node.vm.synced_folder "./data/mnt", "/mnt/", 
    type: "rsync",
    owner: "nobody",
    group: "nogroup"
    # sshfs_opts_append: "-o nonempty -o cache=no"

    node.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get -y install nginx
      # openssl genrsa 2048 > server.key
      # openssl req -new -key server.key -subj "/C=AU/ST=Home/L=Laptop/O=Personal/OU=Local Machine/CN=local-1.vm" > server.csr
      # openssl x509 -days 3650 -req -signkey server.key < server.csr > server.crt
      # mv server.* /etc/letsencrypt/live/

      # TEMPORARY NFS
      apt-get install -y nfs-kernel-server
      mkdir -p /mnt/sharedfolder
      # chown nobody:nogroup /mnt/sharedfolder
      chmod 777 /mnt/sharedfolder
      echo '/mnt/sharedfolder *(rw,fsid=1,sync,no_subtree_check,no_root_squash,insecure)' > /etc/exports
      exportfs -vfa
      systemctl restart nfs-server
    SHELL
  end
end
