---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-integrator-jenkins
  namespace: jenkins
  labels:
    app: vault-agent
spec:
  selector:
    matchLabels:
      app: vault-kube-integrator
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject-secret-app.json: "jenkins/kv/app"
        vault.hashicorp.com/agent-inject-template-app.json: |
          {{- with secret "jenkins/kv/app" -}}
          {
            "apiVersion": "v1",
            "kind": "Secret",
            "metadata": {
              "name": "stable-jenkins-2-5-3"
            },
            "type": "Opaque",
            "stringData": {
            {{ range $k, $v := .Data.data }}
            "{{ $k }}": "{{ $v }}",
            {{ end }}
            "end": "NULL"
            }
          }
          {{- end }}
        vault.hashicorp.com/role: "jenkins"
      labels:
        app: vault-kube-integrator
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 0
      serviceAccountName: stable-jenkins-2-5-3
      containers:
      - name: app
        image: bitnami/kubectl:1.17.4
        command: ["bash"]
        livenessProbe:
          exec:
            command:
            - kubectl
            - apply 
            - -f
            - /vault/secrets/
          initialDelaySeconds: 5
          periodSeconds: 5
        tty: true
...