---
# Source: metricbeat/charts/kube-state-metrics/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    helm.sh/chart: kube-state-metrics-2.4.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: metricbeat-7-8-0
  name: metricbeat-7-8-0-kube-state-metrics
imagePullSecrets:
  []
