---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault
  labels:
    app: vault
    component: server
    release: vault 
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 8Gi
  nfs:
    server: 10.8.41.10
    path: /mnt/sharedfolder/vault/data
