---
# Source: harbor/templates/trivy/trivy-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: stable-harbor-1-4-0-harbor-trivy
  labels:
    heritage: Helm
    release: stable-harbor-1-4-0
    chart: harbor
    app: "harbor"
type: Opaque
data:
  redisURL: cmVkaXM6Ly9zdGFibGUtaGFyYm9yLTEtNC0wLWhhcmJvci1yZWRpczo2Mzc5LzU=
  gitHubToken: ""
