---
# Source: vault/templates/injector-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stable-vault-0.6.0-agent-injector-binding
  labels:
    app.kubernetes.io/name: vault-agent-injector
    app.kubernetes.io/instance: stable-vault-0.6.0
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stable-vault-0.6.0-agent-injector-clusterrole
subjects:
- kind: ServiceAccount
  name: stable-vault-0.6.0-agent-injector
  namespace: vault
