---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
  labels:
    app: prometheus
    component: server
    release: prometheus-11-6-0
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    server: 10.8.41.11
    path: /mnt/sharedfolder/prometheus
