---
# Source: prometheus/templates/node-exporter-service.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    component: "node-exporter"
    app: prometheus
    release: prometheus-11-6-0
    chart: prometheus-11.6.0
    heritage: Helm
  name: prometheus-11-6-0-node-exporter
  namespace: prometheus
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    component: "node-exporter"
    app: prometheus
    release: prometheus-11-6-0
  type: "ClusterIP"
