---
# Source: prometheus/templates/pushgateway-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: "pushgateway"
    app: prometheus
    release: prometheus-11-6-0
    chart: prometheus-11.6.0
    heritage: Helm
  name: prometheus-11-6-0-pushgateway
  namespace: prometheus
spec:
  selector:
    matchLabels:
      component: "pushgateway"
      app: prometheus
      release: prometheus-11-6-0
  replicas: 1
  template:
    metadata:
      labels:
        component: "pushgateway"
        app: prometheus
        release: prometheus-11-6-0
        chart: prometheus-11.6.0
        heritage: Helm
    spec:
      serviceAccountName: prometheus-11-6-0-pushgateway
      containers:
        - name: prometheus-pushgateway
          image: "prom/pushgateway:v1.2.0"
          imagePullPolicy: "IfNotPresent"
          args:
          ports:
            - containerPort: 9091
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          resources:
            {}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
