---
# Source: elastic-stack/charts/elasticsearch/templates/data-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: elasticsearch
    chart: elasticsearch-1.32.0
    component: "data"
    heritage: Helm
    release: elasticstack-0-11-1
  name: elasticstack-0-11-1-elasticsearch-data
