---
# Source: traefik/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: stable-traefik-1-87-1
  labels:
    app: traefik
    chart: traefik-1.87.1
    release: "stable-traefik-1-87-1"
    heritage: "Helm"
data:
  traefik.toml: |
    # traefik.toml
    logLevel = "info"
    defaultEntryPoints = ["http", "httpn"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
      [entryPoints.httpn]
      address = ":8880"
      compress = true
    [ping]
    entryPoint = "http"
    [kubernetes]
    [traefikLog]
      format = "json"
