---
# Source: elasticsearch/templates/client-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: elasticsearch
    chart: elasticsearch-1.32.5
    component: "client"
    heritage: Helm
    release: elasticstack-0-11-1
  name: elasticstack-0-11-1-elasticsearch-client
