---
# Source: loki-stack/charts/promtail/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loki-stack-0-38-2-promtail
  namespace: loki-stack
  labels:
    app: promtail
    chart: promtail-0.23.4
    heritage: Helm
    release: loki-stack-0-38-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: loki-stack-0-38-2-promtail
subjects:
- kind: ServiceAccount
  name: loki-stack-0-38-2-promtail
