---
# Source: loki-stack/charts/promtail/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: promtail
    chart: promtail-0.23.4
    heritage: Helm
    release: loki-stack-0-38-2
  name: loki-stack-0-38-2-promtail
  namespace: loki-stack
