---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: db-clusterrolebinding
  labels:
    app.kubernetes.io/name: db
subjects:
  - kind: ServiceAccount
    name: db
    namespace: db
roleRef:
  kind: ClusterRole
  name: db-clusterrole
  apiGroup: rbac.authorization.k8s.io
