---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: db-rolebind
  namespace: db
subjects:
  - kind: ServiceAccount
    name: db
    namespace: gw-cloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: db-clusterrole