---
# Source: harbor/templates/clair/clair-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: stable-harbor-1-4-0-harbor-clair
  labels:
    heritage: Helm
    release: stable-harbor-1-4-0
    chart: harbor
    app: "harbor"
type: Opaque
data:
  config.yaml: Y2xhaXI6CiAgZGF0YWJhc2U6CiAgICB0eXBlOiBwZ3NxbAogICAgb3B0aW9uczoKICAgICAgc291cmNlOiAicG9zdGdyZXM6Ly9wb3N0Z3JlczpjaGFuZ2VpdEBzdGFibGUtaGFyYm9yLTEtNC0wLWhhcmJvci1kYXRhYmFzZTo1NDMyL3Bvc3RncmVzP3NzbG1vZGU9ZGlzYWJsZSIKICAgICAgIyBOdW1iZXIgb2YgZWxlbWVudHMga2VwdCBpbiB0aGUgY2FjaGUKICAgICAgIyBWYWx1ZXMgdW5saWtlbHkgdG8gY2hhbmdlIChlLmcuIG5hbWVzcGFjZXMpIGFyZSBjYWNoZWQgaW4gb3JkZXIgdG8gc2F2ZSBwcmV2ZW50IG5lZWRsZXNzIHJvdW5kdHJpcHMgdG8gdGhlIGRhdGFiYXNlLgogICAgICBjYWNoZXNpemU6IDE2Mzg0CiAgYXBpOgogICAgIyBBUEkgc2VydmVyIHBvcnQKICAgIHBvcnQ6IDYwNjAKICAgIGhlYWx0aHBvcnQ6IDYwNjEKICAgICMgRGVhZGxpbmUgYmVmb3JlIGFuIEFQSSByZXF1ZXN0IHdpbGwgcmVzcG9uZCB3aXRoIGEgNTAzCiAgICB0aW1lb3V0OiAzMDBzCiAgdXBkYXRlcjoKICAgIGludGVydmFsOiAxMmgK
  redis: cmVkaXM6Ly9zdGFibGUtaGFyYm9yLTEtNC0wLWhhcmJvci1yZWRpczo2Mzc5LzQ=
  database: cG9zdGdyZXM6Ly9wb3N0Z3JlczpjaGFuZ2VpdEBzdGFibGUtaGFyYm9yLTEtNC0wLWhhcmJvci1kYXRhYmFzZTo1NDMyL3Bvc3RncmVzP3NzbG1vZGU9ZGlzYWJsZQ==
