---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-mysql-1
  labels:
    app: mysql
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/sharedfolder/db/mysql/1
    server: 10.8.41.11
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-mysql-2
  labels:
    app: mysql
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/sharedfolder/db/mysql/2
    server: 10.8.41.11
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-mysql-3
  labels:
    app: mysql
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/sharedfolder/db/mysql/3
    server: 10.8.41.11