---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-mysql
  labels:
    app: mysql
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/sharedfolder/db/mysql/
    server: 10.8.41.11