---
# Source: mysql/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: stable-mysql-1-6-4
  namespace: db
  labels:
    app: stable-mysql-1-6-4
    chart: "mysql-1.6.4"
    release: "stable-mysql-1-6-4"
    heritage: "Helm"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
