---
# Source: mysql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: stable-mysql-1-6-4
  namespace: db
  labels:
    app: stable-mysql-1-6-4
    chart: "mysql-1.6.4"
    release: "stable-mysql-1-6-4"
    heritage: "Helm"
type: Opaque
data:
  
  
  mysql-root-password: "UFJkSW5PN2w3NQ=="
  
  
  
  
  mysql-password: "OFY4a01xQjV4WA=="
