---
# Source: harbor/templates/notary/notary-server.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-harbor-1-4-0-harbor-notary-server
  labels:
    heritage: Helm
    release: stable-harbor-1-4-0
    chart: harbor
    app: "harbor"
    component: notary-server
spec:
  replicas: 1
  selector:
    matchLabels:
      release: stable-harbor-1-4-0
      app: "harbor"
      component: notary-server
  template:
    metadata:
      labels:
        heritage: Helm
        release: stable-harbor-1-4-0
        chart: harbor
        app: "harbor"
        component: notary-server
      annotations:
        checksum/secret: 95ff6923eb50e34ff674f9800768bac47c29dd17f7fc371017d5bdd26ece2275
        checksum/secret-core: b87c0147d5d370ec62b7c28d8505cbadaca407cc42be5829353a63721e92d2ba
    spec:
      securityContext:
        fsGroup: 10000
      containers:
      - name: notary-server
        image: goharbor/notary-server-photon:v2.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: MIGRATIONS_PATH
          value: migrations/server/postgresql
        - name: DB_URL
          value: postgres://postgres:changeit@stable-harbor-1-4-0-harbor-database:5432/notaryserver?sslmode=disable
        volumeMounts:
        - name: config
          mountPath: /etc/notary/server-config.postgres.json
          subPath: server.json
        - name: token-service-certificate
          mountPath: /root.crt
          subPath: tls.crt
        - name: signer-certificate
          mountPath: /etc/ssl/notary/ca.crt
          subPath: ca.crt
      volumes:
      - name: config
        secret:
          secretName: "stable-harbor-1-4-0-harbor-notary-server"
      - name: token-service-certificate
        secret:
          secretName: stable-harbor-1-4-0-harbor-core
      - name: signer-certificate
        secret:
          secretName: stable-harbor-1-4-0-harbor-notary-server
