# -*- mode: ruby -*-
# vi: set ft=ruby :
HOSTNAME = "local"
PRIVATE_SUBNET = "10.8.0"
PUBLIC_SUBNET = "172.17.8"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vagrant.plugins = ["dns"]
  config.dns.tld = "vm"
  config.dns.patterns = [/^(\w+\.)*#{HOSTNAME}\.vm$/]
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.hostname = "#{HOSTNAME}-1"

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/bionic64"

  config.vm.network "forwarded_port", guest: 22, host: 2525

  config.vm.network "private_network", ip: "#{PRIVATE_SUBNET}.10"
  config.vm.network "private_network", ip: "#{PUBLIC_SUBNET}.10"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y nginx
    # apt-get install -y nfs-kernel-server
    # mkdir -p /mnt/sharedfolder
    # chown nobody:nogroup /mnt/sharedfolder
    # chmod 777 /mnt/sharedfolder
    # echo '/mnt/sharedfolder *(rw,sync,no_subtree_check,no_root_squash,insecure)' > /etc/exports
    # exportfs -vfa
    # systemctl restart nfs
  SHELL
end
