---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-chartmuseum
  labels:
    heritage: Helm
    release: stable-harbor-1-4-0
    chart: harbor
    app: "harbor"
    component: chartmuseum
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  nfs:
    server: 10.8.41.10
    path: /mnt/sharedfolder/harbor/chartmuseum
