---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-redis
  labels:
    app: harbor
    chart: harbor
    component: redis
    controller-revision-hash: stable-harbor-1-4-0-harbor-redis-7f7fc5d466
    heritage: Helm
    release: stable-harbor-1-4-0
    statefulset.kubernetes.io/pod-name: stable-harbor-1-4-0-harbor-redis-0
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  nfs:
    server: 10.8.41.10
    path: /mnt/sharedfolder/harbor/redis
