---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-trivy
  labels:
    app: harbor
    chart: harbor
    component: trivy
    controller-revision-hash: stable-harbor-1-4-0-harbor-trivy-587bb86df7
    heritage: Helm
    release: stable-harbor-1-4-0
    statefulset.kubernetes.io/pod-name: stable-harbor-1-4-0-harbor-trivy-0
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  nfs:
    server: 10.8.41.10
    path: /mnt/sharedfolder/harbor/trivy
