---
# Source: harbor/templates/database/database-ss.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "stable-harbor-1-4-0-harbor-database"
  labels:
    heritage: Helm
    release: stable-harbor-1-4-0
    chart: harbor
    app: "harbor"
    component: database
spec:
  replicas: 1
  serviceName: "stable-harbor-1-4-0-harbor-database"
  selector:
    matchLabels:
      release: stable-harbor-1-4-0
      app: "harbor"
      component: database
  template:
    metadata:
      labels:
        heritage: Helm
        release: stable-harbor-1-4-0
        chart: harbor
        app: "harbor"
        component: database
      annotations:
        checksum/secret: 86a6228951622362ac4ac43ed8295bf7d9bed9bcb4c48c900ed4017dd5190baf
    spec:
      # initContainers:
      # - name: "change-permission-of-directory"
      #   image: busybox:latest
      #   imagePullPolicy: IfNotPresent
      #   command: ["/bin/sh"]
      #   args: ["-c", "chown -R 999:999 /var/lib/postgresql/data"]
      #   volumeMounts:
      #   - name: database-data
      #     mountPath: /var/lib/postgresql/data
      #     subPath: ""
      # - name: "remove-lost-found"
      #   image: goharbor/harbor-db:v2.0.0
      #   imagePullPolicy: IfNotPresent
      #   command: ["rm", "-Rf", "/var/lib/postgresql/data/lost+found"]
      #   volumeMounts:
      #   - name: database-data
      #     mountPath: /var/lib/postgresql/data
      #     subPath: ""
      containers:
      - name: database
        image: goharbor/harbor-db:v2.0.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /docker-healthcheck.sh
          initialDelaySeconds: 300
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /docker-healthcheck.sh
          initialDelaySeconds: 1
          periodSeconds: 10
        envFrom:
          - secretRef:
              name: "stable-harbor-1-4-0-harbor-database"
        volumeMounts:
        - name: database-data
          mountPath: /var/lib/postgresql/data
          subPath: 
  volumeClaimTemplates:
  - metadata:
      name: "database-data"
      labels:
        heritage: Helm
        release: stable-harbor-1-4-0
        chart: harbor
        app: "harbor"
        component: database
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: "1Gi"
