---
# Source: harbor/templates/database/database-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: "stable-harbor-1-4-0-harbor-database"
  labels:
    heritage: Helm
    release: stable-harbor-1-4-0
    chart: harbor
    app: "harbor"
spec:
  ports:
    - port: 5432
  selector:
    release: stable-harbor-1-4-0
    app: "harbor"
    component: database
