---
# Source: elastic-stack/charts/kibana/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kibana
    chart: "kibana-3.2.4"
    heritage: Helm
    release: elasticstack-0-11-1
  name: elasticstack-0-11-1-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
      release: elasticstack-0-11-1
  revisionHistoryLimit: 3
  template:
    metadata:
      annotations:
        checksum/config: 1e54491d06457e9e32d6fae6c9fd3506b53f3a66a6aac0aaeff3b686c314cd17
      labels:
        app: kibana
        release: "elasticstack-0-11-1"
    spec:
      serviceAccountName: default
      containers:
      - name: kibana
        image: "docker.elastic.co/kibana/kibana-oss:6.7.0"
        imagePullPolicy: IfNotPresent
        env:
        - name: "ELASTICSEARCH_HOSTS"
          value: "http://elasticstack-0-11-1-elasticsearch-client:9200"
        ports:
        - containerPort: 5601
          name: kibana
          protocol: TCP
        resources:
          {}
        volumeMounts:
        - name: kibana
          mountPath: "/usr/share/kibana/config/kibana.yml"
          subPath: kibana.yml
      tolerations:
        []
      volumes:
        - name: kibana
          configMap:
            name: elasticstack-0-11-1-kibana
