apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: grafana
spec:
  project: operations
  source:
    repoURL: 'https://github.com/jesmigel/jc_infrastructure.git'
    path: ops/monitor/grafana
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana