apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  project: operations
  source:
    repoURL: 'https://github.com/jesmigel/jc_infrastructure.git'
    path: ops/monitor/loki
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: loki-stack