apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: operations
  source:
    repoURL: 'https://github.com/jesmigel/jc_infrastructure.git'
    path: ops/network/nginxinc
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nginx-ingress