---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault
  labels:
    helm.sh/chart: vault-0.6.0
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: stable-vault-0-6-0
    component: server
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    server: 10.8.41.11
    path: /mnt/sharedfolder/vault/data
