resources:
  - ns.yaml
  - pv.elasticsearch.yaml
  - pv.logstash.yaml
  - kibana/templates/deployment.yaml
  - kibana/templates/ingress.yaml
  - kibana/templates/service.yaml
  - elasticsearch/templates/service.yaml
  - elasticsearch/templates/poddisruptionbudget.yaml
  - elasticsearch/templates/statefulset.yaml