---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data-1
  labels:
    app: elasticsearch
    chart: elasticsearch-1.32.0
    component: "data"
    heritage: Helm
    release: stable-elk-2-0-1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 30Gi
  nfs:
    server: 10.8.41.10
    path: /mnt/sharedfolder/elastic-stack/elasticsearch/data/1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data-2
  labels:
    app: elasticsearch
    chart: elasticsearch-1.32.0
    component: "data"
    heritage: Helm
    release: stable-elk-2-0-1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 30Gi
  nfs:
    server: 10.8.41.10
    path: /mnt/sharedfolder/elastic-stack/elasticsearch/data/2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-master-1
  labels:
    heritage: "Helm"
    release: "elasticsearch-7-8-0"
    chart: "elasticsearch"
    app: "elasticsearch-master"
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 4Gi
  nfs:
    server: 10.8.41.10
    path: /mnt/sharedfolder/elastic-stack/elasticsearch/master/1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-master-2
  labels:
    heritage: "Helm"
    release: "elasticsearch-7-8-0"
    chart: "elasticsearch"
    app: "elasticsearch-master"
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 4Gi
  nfs:
    server: 10.8.41.10
    path: /mnt/sharedfolder/elastic-stack/elasticsearch/master/2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-master-3
  labels:
    heritage: "Helm"
    release: "elasticsearch-7-8-0"
    chart: "elasticsearch"
    app: "elasticsearch-master"
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 4Gi
  nfs:
    server: 10.8.41.10
    path: /mnt/sharedfolder/elastic-stack/elasticsearch/master/3