---
# Source: elastic-stack/charts/elasticsearch/templates/master-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: elasticsearch
    chart: elasticsearch-1.32.0
    component: "master"
    heritage: Helm
    release: stable-elk-2-0-1
  name: stable-elk-2-0-1-elasticsearch-master
