---
# Source: metricbeat/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metricbeat-7-8-0-metricbeat
  labels:
    app: "metricbeat-7-8-0-metricbeat"
    chart: "metricbeat-7.8.0"
    heritage: "Helm"
    release: "metricbeat-7-8-0"
