---
# Source: nfs-client-provisioner/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.8
    heritage: Helm
    release: stable-nfs-client-provisioner-1-2-8
  name: run-stable-nfs-client-provisioner-1-2-8
subjects:
  - kind: ServiceAccount
    name: stable-nfs-client-provisioner-1-2-8
    namespace: default
roleRef:
  kind: ClusterRole
  name: stable-nfs-client-provisioner-1-2-8-runner
  apiGroup: rbac.authorization.k8s.io
