---
# Source: nfs-client-provisioner/templates/rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.8
    heritage: Helm
    release: stable-nfs-client-provisioner-1-2-8
  name: leader-locking-stable-nfs-client-provisioner-1-2-8
subjects:
  - kind: ServiceAccount
    name: stable-nfs-client-provisioner-1-2-8
    namespace: default
roleRef:
  kind: Role
  name: leader-locking-stable-nfs-client-provisioner-1-2-8
  apiGroup: rbac.authorization.k8s.io
