---
# Source: nfs-client-provisioner/templates/rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.9
    heritage: Helm
    release: nfs-stable
  name: leader-locking-nfs-stable-nfs-client-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-stable-nfs-client-provisioner
    namespace: nfs
roleRef:
  kind: Role
  name: leader-locking-nfs-stable-nfs-client-provisioner
  apiGroup: rbac.authorization.k8s.io
