---
# Source: consul/templates/client-clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stable-consul-0-21-0-consul-client
  labels:
    app: consul
    chart: consul-helm
    heritage: Helm
    release: stable-consul-0-21-0
rules:
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    resourceNames:
    - stable-consul-0-21-0-consul-client
    verbs:
    - use
  - apiGroups: [""]
    resources:
      - secrets
    resourceNames:
      - stable-consul-0-21-0-consul-client-acl-token
    verbs:
      - get
