---
# Source: consul/templates/server-acl-init-podsecuritypolicy.yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: stable-consul-0-21-0-consul-server-acl-init
  labels:
    app: consul
    chart: consul-helm
    heritage: Helm
    release: stable-consul-0-21-0
spec:
  privileged: false
  # Allow core volume types.
  volumes:
    - 'secret'
  allowPrivilegeEscalation: false
  # This is redundant with non-root + disallow privilege escalation,
  # but we can provide it for defense in depth.
  requiredDropCapabilities:
    - ALL
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
