---
# Source: consul/templates/server-acl-init-cleanup-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stable-consul-0-21-0-consul-server-acl-init-cleanup
  namespace: consul
  labels:
    app: consul
    chart: consul-helm
    heritage: Helm
    release: stable-consul-0-21-0
