---
# Source: consul/templates/server-acl-init-cleanup-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stable-consul-0-21-0-consul-server-acl-init-cleanup
  labels:
    app: consul
    chart: consul-helm
    heritage: Helm
    release: stable-consul-0-21-0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stable-consul-0-21-0-consul-server-acl-init-cleanup
subjects:
  - kind: ServiceAccount
    name: stable-consul-0-21-0-consul-server-acl-init-cleanup
    namespace: consul
