---
# Source: harbor/templates/notary/notary-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: stable-harbor-1-4-0-harbor-notary-server
  labels:
    heritage: Helm
    release: stable-harbor-1-4-0
    chart: harbor
    app: "harbor"
spec:
  ports:
  - port: 4443
  selector:
    release: stable-harbor-1-4-0
    app: "harbor"
    component: notary-server
---
# Source: harbor/templates/notary/notary-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: stable-harbor-1-4-0-harbor-notary-signer
  labels:
    heritage: Helm
    release: stable-harbor-1-4-0
    chart: harbor
    app: "harbor"
spec:
  ports:
  - port: 7899
  selector:
    release: stable-harbor-1-4-0
    app: "harbor"
    component: notary-signer
