---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wpblog-mariadb
  labels:
    app: mariadb
    chart: mariadb-7.5.2
    release: bitnami-wordpress-9-3-15
    heritage: Helm
    component: master
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  nfs:
    server: 10.8.41.10
    path: /mnt/sharedfolder/wpblog/mariadb