apiVersion: v1
data:
  admin.enabled: "true"
  repositories: |
    - name: vault
      type: helm
      url: https://helm.releases.hashicorp.com
    - name: CNCF
      type: helm
      url: https://kubernetes-charts.storage.googleapis.com
    - type: git
      url: https://github.com/jesmigel/jc_infrastructure.git
  resource.customizations: |
    networking.k8s.io/Ingress:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        return hs
    admissionregistration.k8s.io/MutatingWebhookConfiguration:
      ignoreDifferences: |
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
    manager: argocd-server
  name: argocd-cm
  namespace: argocd