apiVersion: v1
data:
  admin.enabled: "true"
  repositories: |
    - name: vault
      type: helm
      url: https://helm.releases.hashicorp.com
    - name: CNCF
      type: helm
      url: https://kubernetes-charts.storage.googleapis.com
    - type: git
      url: https://github.com/jesmigel/jc_infrastructure.git
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
    manager: argocd-server
  name: argocd-cm
  namespace: argocd